### ISSUE TITLE
Usuarios

### ISSUE THREAD

**Issue by juandjara** [JuanLSanchez/datask#2]
- [x] Lista paginada de usuarios filtrable por nombre
- [x] Crear usuario
- [x] Editar usuario
- [x] Borrar usuario

Esta parte de la API es muy parecida a lo que tenemos en `otbconfig`
Esta parte de la API solo podrá ser accedida para aquellos usuarios con rol ADMIN

**Comment by JuanLSanchez** [comment]
¿Los usuarios pueden modificar alguno de sus datos?

**Comment by juandjara** [comment]
Un usuario puede modificar sus datos personales, como nombre, apellido, email y telefono (de la oficina).
Esto es lo que en `JHipster` se hace haciendo un `POST` al endpoint `/account`

**Comment by JuanLSanchez** [comment]
Actualmente, el usuario puede modificar todos sus datos a excepción de sus roles y login.

**Comment by JuanLSanchez** [comment]
Esta tarea ya esta resulta, confírmame cuando este validada
