### ISSUE TITLE
Empresas

### ISSUE THREAD

**Issue by juandjara** [JuanLSanchez/datask#4]
### Entidad
- [x] Lista paginada de empresas
- [x] Crear empresa
- [x] Editar empresa
- [x] Borrar empresa

### Relaciones
- [x] Añadir un usuario ya existente a una empresa
- [x] Sacar a un usuario de una empresa (sin borrar el usuario)

**Comment by JuanLSanchez** [comment]
Supongo que esto solo lo podrán hacer los usuarios con roles admin y manager, ¿no?

**Comment by juandjara** [comment]
Si, de hecho no acabo de entender muy bien el rol manager. ¿Puede hacer todo lo que hace el admin menos crear usuarios?

**Comment by JuanLSanchez** [comment]
Un usuario solo puede estar en una empresa, por lo que la funcionalidad de añadir usuarios a empresas lo he añadido en la creación/edición de usuarios.
